In [140]:
import pandas as pd
import numpy as np
from sklearn.metrics import mean_squared_error
from sklearn.linear_model import LinearRegression
from sklearn import metrics

In [100]:
col_names = ['s2', 's3', 's4', 's7', 's11', 's12', 's13', 's14', 's15', 's17', 's20', 's21']
data_train = pd.read_csv('data/train.csv')
data_test = pd.read_csv('data/test.csv')
X_train =data_train[col_names]
y_train = data_train['ttf']
X_test = data_test[col_names]
y_test = data_test['ttf']

## áp dụng công thức

In [157]:
A = np.dot(X_train.T, X_train)
b = np.dot(X_train.T, y_train)
w = np.dot(np.linalg.pinv(A), b)
# hệ số hồi quy
w

array([  -7.17788005,   -0.46688868,   -0.81087475,    7.27680854,
        -39.26797485,   11.23344517,    1.53139891,   -0.62051656,
       -127.24634018,   -2.00137619,   21.19163517,   43.95098003])

In [163]:
y_pred = np.sum(w*X_test,axis = 1)
y_pred

0     161.744788
1     121.213579
2      82.830134
3      96.177645
4     114.946337
         ...    
95    165.558223
96    107.507204
97     96.566525
98    161.230198
99      4.382773
Length: 100, dtype: float64

## áp dụng hàm có sẵn

In [150]:
regression = LinearRegression()
regression.fit(X_train, y_train)
# hệ số hồi quy
w1 = regression.coef_
w1

array([  -7.08623508,   -0.4596332 ,   -0.79636225,    7.09689047,
        -38.58435669,   10.95862007,  -13.49193377,   -0.63812921,
       -125.07937558,   -1.96193866,   20.74912844,   43.1220217 ])

In [152]:
w0 =  regression.intercept_ 
w0

36142.750327205395

In [166]:
y_pred = w0 + np.sum(w1*X_test,axis = 1)
y_pred

0     161.654513
1     121.517581
2      83.044663
3      96.480562
4     114.582613
         ...    
95    165.591838
96    107.704936
97     96.765383
98    161.148790
99      4.949056
Length: 100, dtype: float64

In [136]:
y_pred = regression.predict(X_test)
y_pred

array([161.65451256, 121.51758119,  83.04466309,  96.48056154,
       114.58261333, 121.6313789 , 131.08481981,  95.87029293,
       114.51148866, 117.40683296,  98.90946703, 111.47288134,
        99.70624192, 114.79500736, 162.06372836, 137.04400232,
        81.52368755,  79.14452195, 122.38472551,  23.6640085 ,
       118.99599033, 143.38694699, 154.4773464 ,  33.6899708 ,
       137.06222127, 143.67465931, 129.58768515, 113.90708685,
       126.21729615,  99.44993644,  12.19215283, 108.12518069,
       108.0651611 ,   6.59709218,  -0.60986656,  34.81273722,
        81.51539197,  69.39779056, 154.6695948 ,  37.93732071,
        92.70554016,  36.91179697,  78.0359954 , 121.29685799,
        85.43464068,  67.38759629, 123.7073496 , 119.45573644,
        20.81957288, 127.99232267, 120.76360422,  50.63997706,
        41.57263569, 170.131978  , 140.8790971 ,  36.25243425,
       104.37003496,  72.69633097, 164.06834611, 117.60016632,
        52.64111105,  89.85904457,  84.71594426,  66.27

In [137]:
# R bình % của dự đoán
r_sq = regression.score(X_test, y_test)
r_sq 

0.41504559932988916

In [142]:
metrics.mean_absolute_error(y_test, y_pred)

25.44318539541935

In [146]:
np.sqrt(metrics.mean_squared_error(y_test, y_pred))

31.78269925452264

In [148]:
df = pd.DataFrame({'thực': y_test, 'dự đoán': y_pred})
df

thực     dự đoán
0    112  161.654513
1     98  121.517581
2     69   83.044663
3     82   96.480562
4     91  114.582613
..   ...         ...
95   137  165.591838
96    82  107.704936
97    59   96.765383
98   117  161.148790
99    20    4.949056

[100 rows x 2 columns]